services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: velocira-postgres
    environment:
      POSTGRES_DB: velocira_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - velocira-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  velocira-pg-data:
