import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2 } from "lucide-react";
import Button from "@/components/ui/Button";
import Card from "@/components/ui/Card";
import SignalForgeVisual from "@/components/ui/SignalForgeVisual";
import { FadeIn, PageTransition } from "@/components/ui/Animations";

const steps = ["Create a project with a clear title and short description.", "Answer the focused discovery questions on the project page.", "Generate the SRS directly from those answers, with an optional source file when you want richer citations.", "Generate the linked package and download the format your team needs."];

export default function DocsPage() {
  return <PageTransition><section className="public-page"><section className="public-hero public-hero--visual public-hero--compact"><div className="public-hero__content"><p className="public-eyebrow"><BookOpen className="h-4 w-4" /> Getting started</p><h1>Four direct steps. One project page.</h1><p className="public-hero__copy">Velocira keeps the workflow visible from start to finish. There are no separate confirmation or review pages between your answers and generation.</p></div><SignalForgeVisual name="documents" priority label="Documentation package preview" /></section><FadeIn className="mt-6"><Card className="p-4 sm:p-6"><ol className="space-y-2">{steps.map((step, index) => <li key={step} className="flex gap-4 rounded-md border border-transparent px-3 py-3 text-sm leading-6 text-foreground-secondary hover:border-border hover:bg-background-secondary/50"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-accent text-xs font-bold text-on-primary">{index + 1}</span><span className="pt-0.5">{step}</span></li>)}</ol></Card></FadeIn><FadeIn className="mt-5" delay={0.06}><Card className="flex gap-3 border-accent/25 bg-accent-light p-5"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-success" /><p className="text-sm leading-6 text-foreground-secondary">Generation preserves the original project answers and source context alongside each output, so your team can always see what informed it.</p></Card></FadeIn><FadeIn className="mt-5 sf-visual-frame" delay={0.1}><div className="sf-visual-frame__header"><p>Connected source context</p><span>Evidence to output</span></div><SignalForgeVisual name="traceability" label="Traceability evidence map" /></FadeIn><Link href="/projects" className="mt-7 inline-block"><Button icon={<ArrowRight className="h-4 w-4" />}>Open projects</Button></Link></section></PageTransition>;
}
